var rate = document.getElementById("rate");
var reviews = document.getElementById("reviews");
var prep = document.getElementById("prep-time");
var cook = document.getElementById("cook-time");
var Servings = document.getElementById("Servings");
var level = document.getElementById("level");
var country = document.getElementById("country");
var recipeTitle = document.getElementById("recipeTitle");
var recipeDescription = document.getElementById("recipeDescription");
var recipe_Alert = document.getElementById("recipeAlert");
var Calories = document.getElementById("Calories");
var Protein = document.getElementById("Protein");
var Carbohydrates = document.getElementById("Carbohydrates");
var Fat = document.getElementById("Fat");
var Fiber = document.getElementById("Fiber");
var Sodium = document.getElementById("Sodium");
var Ingredient = document.getElementById("Ingredient");
var Tips = document.getElementById("Tips");
var Instruction = document.getElementById("Instruction");
var image = document.getElementById("image");

var recipe = [
  {
    img: "images/Carbonara.avif",
    rate: "4.8",
    review: "(234 reviews)",
    prep: "15 min",
    cook: "20 min",
    serve: "4 people",
    level: "Easy",
    country: "Italian",
    recipeTitle: "Creamy Spaghetti Carbonara",
    recipeDescription:
      "A classic Italian pasta dish with eggs, cheese, and pancetta",
    recipeAlert: false,
    Calories: "520 kcal",
    Protein: "28g",
    Carbohydrates: "62g",
    Fat: "18g",
    Fiber: "3g",
    Sodium: "680mg",
    IngredientList: [
      "400g spaghetti pasta",
      "200g pancetta or guanciale, diced",
      "4 large eggs",
      "100g Pecorino Romano cheese, grated",
      "50g Parmesan cheese, grated",
      "Freshly ground black pepper",
      "Salt for pasta water",
    ],
    InstructionList: [
      "Bring a large pot of salted water to boil. Cook spaghetti according to package directions until al dente.",
      "While pasta cooks, heat a large skillet over medium heat. Add diced pancetta and cook until crispy, about 5-7 minutes.",
      "In a bowl, whisk together eggs, grated Pecorino Romano, and Parmesan cheese. Add plenty of freshly ground black pepper.",
      "Reserve 1 cup of pasta cooking water before draining. Drain pasta and immediately add to the skillet with pancetta.",
      "Remove skillet from heat. Quickly pour in egg mixture while tossing pasta vigorously. Add reserved pasta water as needed to create a creamy sauce.",
      "Serve immediately with extra cheese and black pepper on top.",
    ],
    tipList: [
      "Use room temperature eggs for a smoother sauce consistency",
      "Work quickly when mixing eggs with hot pasta to avoid scrambling",
      "Reserve extra pasta water - it's the secret to perfect creaminess",
      "Freshly grated cheese makes all the difference in flavor",
      "Never add cream - authentic carbonara is made with eggs only",
    ],
  },

  {
    img: "images/Salmon.avif",
    rate: "4.9",
    review: "(187 reviews)",
    prep: "10 min",
    cook: "15 min",
    serve: "2 people",
    level: "Easy",
    country: "Seafood",
    recipeTitle: "Honey Garlic Salmon",
    recipeDescription: "Pan-seared salmon with a sweet and savory glaze",
    recipeAlert: false,
    Calories: "380 kcal",
    Protein: "35g",
    Carbohydrates: "28g",
    Fat: "14g",
    Fiber: "0g",
    Sodium: "720mg",
    IngredientList: [
      "2 salmon fillets (6oz each)",
      "3 tablespoons honey",
      "2 tablespoons soy sauce",
      "4 cloves garlic, minced",
      "1 tablespoon olive oil",
      "1 teaspoon fresh ginger, grated",
      "Sesame seeds for garnish",
      "Green onions, sliced",
    ],
    InstructionList: [
      "Pat salmon fillets dry with paper towels. Season with salt and pepper.",
      "In a small bowl, whisk together honey, soy sauce, minced garlic, and grated ginger.",
      "Heat olive oil in a large skillet over medium-high heat.",
      "Place salmon fillets skin-side up in the pan. Cook for 4-5 minutes until golden.",
      "Flip salmon and pour honey garlic sauce over the top. Cook for another 4-5 minutes.",
      "Garnish with sesame seeds and sliced green onions. Serve with steamed vegetables or rice.",
    ],
    tipList: [
      "Don't overcook salmon - it should be slightly pink in the center",
      "Use wild-caught salmon for best flavor and nutrition",
      "Let the sauce caramelize slightly for deeper flavor",
      "Pair with steamed broccoli or asparagus for a complete meal",
    ],
  },

  {
    img: "images/Thai.avif",
    rate: "4.7",
    review: "(312 reviews)",
    prep: "15 min",
    cook: "25 min",
    serve: "4 people",
    level: "Intermediate",
    country: "Asian",
    recipeTitle: "Thai Green Curry",
    recipeDescription:
      "Vibrant and aromatic curry with vegetables and coconut milk",
    recipeAlert: false,
    Calories: "420 kcal",
    Protein: "26g",
    Carbohydrates: "22g",
    Fat: "26g",
    Fiber: "5g",
    Sodium: "890mg",
    IngredientList: [
      "2 tablespoons green curry paste",
      "400ml coconut milk",
      "300g chicken breast, sliced",
      "1 red bell pepper, sliced",
      "100g green beans",
      "1 eggplant, cubed",
      "2 tablespoons fish sauce",
      "1 tablespoon palm sugar",
      "Fresh Thai basil leaves",
    ],
    InstructionList: [
      "Heat a large pot or wok over medium heat. Add curry paste and cook for 1 minute until fragrant.",
      "Add half the coconut milk and stir to combine with the curry paste.",
      "Add sliced chicken and cook until no longer pink, about 5 minutes.",
      "Add remaining coconut milk, vegetables, fish sauce, and palm sugar.",
      "Simmer for 15-20 minutes until vegetables are tender and sauce has thickened.",
      "Stir in fresh Thai basil leaves. Serve hot with jasmine rice.",
    ],
    tipList: [
      "Adjust spice level by using more or less curry paste",
      "Add vegetables in stages based on cooking time needed",
      "Fresh Thai basil is essential for authentic flavor",
      "Use full-fat coconut milk for richest, creamiest sauce",
    ],
  },
  {
    img: "images/Beef-Burger.avif",
    rate: "4.6",
    review: "(421 reviews)",
    prep: "15 min",
    cook: "20 min",
    serve: "4 people",
    level: "Easy",
    country: "American",
    recipeTitle: "Classic Beef Burger",
    recipeDescription: "Juicy homemade burger with all the fixings",
    recipeAlert: false,
    Calories: "650 kcal",
    Protein: "38g",
    Carbohydrates: "42g",
    Fat: "35g",
    Fiber: "2g",
    Sodium: "920mg",
    IngredientList: [
      "500g ground beef (80/20)",
      "4 burger buns",
      "4 slices cheddar cheese",
      "Lettuce leaves",
      "Tomato slices",
      "Red onion, sliced",
      "Pickles",
      "Burger sauce or condiments",
    ],
    InstructionList: [
      "Divide ground beef into 4 equal portions. Form into patties, making a small indent in the center.",
      "Season patties generously with salt and pepper on both sides.",
      "Heat a grill or skillet over high heat. Cook patties for 4-5 minutes per side for medium.",
      "Add cheese slices in the last minute of cooking and cover to melt.",
      "Toast burger buns lightly on the grill or in a pan.",
      "Assemble burgers with lettuce, tomato, onion, pickles, and your favorite sauce.",
    ],
    tipList: [
      "Don't press down on burgers while cooking - keeps them juicy",
      "Make indent in center to prevent burger from puffing up",
      "Let patties rest for 2-3 minutes before serving",
      "Toast buns for better texture and flavor",
    ],
  },

  {
    img: "images/Mediterranean.avif",
    rate: "4.5",
    review: "(156 reviews)",
    prep: "20 min",
    cook: "35 min",
    serve: "2 people",
    level: "Easy",
    country: "Mediterranean",
    recipeTitle: "Mediterranean Quinoa Bowl",
    recipeDescription:
      "Healthy bowl with quinoa, vegetables, and tahini dressing",
    recipeAlert: true,
    Calories: "480 kcal",
    Protein: "18g",
    Carbohydrates: "58g",
    Fat: "20g",
    Fiber: "10g",
    Sodium: "540mg",
    IngredientList: [
      "1 cup quinoa",
      "Cherry tomatoes, halved",
      "Cucumber, diced",
      "Red onion, sliced",
      "Kalamata olives",
      "Feta cheese, crumbled",
      "Fresh parsley",
      "Tahini dressing",
    ],
    InstructionList: [
      "Rinse quinoa thoroughly. Cook according to package directions, usually 15 minutes.",
      "While quinoa cooks, prepare all vegetables and set aside.",
      "For tahini dressing: mix tahini, lemon juice, garlic, and water until smooth.",
      "Fluff cooked quinoa with a fork and let cool slightly.",
      "Arrange quinoa in bowls. Top with tomatoes, cucumber, onion, and olives.",
      "Sprinkle with feta cheese and fresh parsley. Drizzle with tahini dressing.",
    ],
    tipList: [
      "Rinse quinoa well to remove bitter coating",
      "Let quinoa cool before adding fresh ingredients",
      "Make extra tahini dressing - it keeps well in the fridge",
      "Add grilled chicken or chickpeas for extra protein",
    ],
  },

  {
    img: "images/Tikka.avif",
    rate: "4.7",
    review: "(389 reviews)",
    prep: "20 min",
    cook: "30 min",
    serve: "4 people",
    level: "Intermediate",
    country: "Asian",
    recipeTitle: "Chicken Tikka Masala",
    recipeDescription:
      "Rich and creamy Indian curry with tender chicken pieces",
    recipeAlert: true,
    Calories: "450 kcal",
    Protein: "38g",
    Carbohydrates: "24g",
    Fat: "22g",
    Fiber: "4g",
    Sodium: "760mg",
    IngredientList: [
      "600g chicken breast, cubed",
      "1 cup plain yogurt",
      "2 tablespoons tikka masala paste",
      "400ml coconut cream",
      "1 onion, diced",
      "4 cloves garlic, minced",
      "2 tablespoons ginger, grated",
      "400g canned tomatoes",
      "Fresh cilantro for garnish",
    ],
    InstructionList: [
      "Marinate chicken in half the yogurt and 1 tablespoon tikka paste for at least 30 minutes.",
      "Heat oil in a large pan, cook marinated chicken until browned. Remove and set aside.",
      "In the same pan, sauté onion until soft. Add garlic and ginger, cook for 1 minute.",
      "Add remaining tikka paste and canned tomatoes. Simmer for 10 minutes.",
      "Stir in coconut cream and remaining yogurt. Add chicken back to the pan.",
      "Simmer for 15 minutes until sauce thickens. Garnish with cilantro and serve with rice.",
    ],
    tipList: [
      "Marinate chicken overnight for deeper flavor",
      "Use full-fat coconut cream for richest sauce",
      "Adjust spice level by varying the tikka paste amount",
      "Serve with naan bread and basmati rice",
    ],
  },
  {
    img: "images/Pizza.avif",
    rate: "4.9",
    review: "(512 reviews)",
    prep: "90 min",
    cook: "12 min",
    serve: "2 people",
    level: "Intermediate",
    country: "Italian",
    recipeTitle: "Margherita Pizza",
    recipeDescription: "Classic Italian pizza with fresh mozzarella and basil",
    recipeAlert: true,
    Calories: "580 kcal",
    Protein: "24g",
    Carbohydrates: "68g",
    Fat: "22g",
    Fiber: "4g",
    Sodium: "920mg",
    IngredientList: [
      "300g pizza dough",
      "200g crushed tomatoes",
      "250g fresh mozzarella",
      "Fresh basil leaves",
      "2 tablespoons olive oil",
      "2 cloves garlic, minced",
      "Salt and pepper to taste",
      "Parmesan cheese for topping",
    ],
    InstructionList: [
      "Let pizza dough come to room temperature and rest for 1 hour.",
      "Preheat oven to maximum temperature.",
      "Mix crushed tomatoes with olive oil, garlic, salt, and pepper.",
      "Roll out dough on a floured surface.",
      "Spread tomato sauce and add mozzarella.",
      "Bake for 10-12 minutes until golden. Add basil and parmesan.",
    ],
    tipList: [
      "Use a pizza stone for crispier crust",
      "Don't overload with toppings",
      "Add basil after baking",
      "Let dough rest properly",
    ],
  },

  {
    img: "images/Tacos.avif",
    rate: "4.6",
    review: "(278 reviews)",
    prep: "15 min",
    cook: "20 min",
    serve: "4 people",
    level: "Easy",
    country: "American",
    recipeTitle: "Beef Tacos",
    recipeDescription: "Flavorful Mexican tacos with seasoned ground beef",
    recipeAlert: false,
    Calories: "420 kcal",
    Protein: "26g",
    Carbohydrates: "32g",
    Fat: "20g",
    Fiber: "4g",
    Sodium: "780mg",
    IngredientList: [
      "500g ground beef",
      "8 taco shells",
      "1 onion, diced",
      "2 tablespoons taco seasoning",
      "Shredded lettuce",
      "Diced tomatoes",
      "Shredded cheddar cheese",
      "Sour cream",
      "Salsa",
    ],
    InstructionList: [
      "Cook ground beef until browned.",
      "Add onion and cook until softened.",
      "Stir in taco seasoning and water.",
      "Warm taco shells.",
      "Fill shells with beef.",
      "Top with lettuce, tomatoes, cheese, sour cream, and salsa.",
    ],
    tipList: [
      "Drain excess fat from beef",
      "Warm shells before serving",
      "Prepare toppings first",
      "Use ground turkey for lighter tacos",
    ],
  },

  {
    img: "images/Caesar.avif",
    rate: "4.4",
    review: "(198 reviews)",
    prep: "15 min",
    cook: "0 min",
    serve: "2 people",
    level: "Easy",
    country: "Mediterranean",
    recipeTitle: "Caesar Salad",
    recipeDescription: "Classic salad with crispy romaine and creamy dressing",
    recipeAlert: false,
    Calories: "320 kcal",
    Protein: "12g",
    Carbohydrates: "18g",
    Fat: "22g",
    Fiber: "3g",
    Sodium: "680mg",
    IngredientList: [
      "1 large romaine lettuce",
      "1/2 cup Caesar dressing",
      "1/2 cup parmesan cheese, shaved",
      "1 cup croutons",
      "2 anchovy fillets (optional)",
      "Lemon wedges",
      "Black pepper",
    ],
    InstructionList: [
      "Wash and dry romaine lettuce thoroughly.",
      "Place lettuce in a large bowl.",
      "Add Caesar dressing and toss.",
      "Add croutons and parmesan.",
      "Top with anchovies if using.",
      "Serve with lemon wedges and black pepper.",
    ],
    tipList: [
      "Use cold crisp lettuce",
      "Make homemade croutons",
      "Add grilled chicken if desired",
      "Dress salad before serving only",
    ],
  },

  {
    img: "images/Pad-Thai.avif",
    rate: "4.8",
    review: "(445 reviews)",
    prep: "20 min",
    cook: "15 min",
    serve: "2 people",
    level: "Intermediate",
    country: "Asian",
    recipeTitle: "Pad Thai",
    recipeDescription:
      "Popular Thai stir-fried noodles with shrimp and peanuts",
    recipeAlert: false,
    Calories: "540 kcal",
    Protein: "32g",
    Carbohydrates: "62g",
    Fat: "16g",
    Fiber: "4g",
    Sodium: "1120mg",
    IngredientList: [
      "200g rice noodles",
      "200g shrimp, peeled",
      "2 eggs",
      "3 tablespoons tamarind paste",
      "2 tablespoons fish sauce",
      "1 tablespoon palm sugar",
      "Bean sprouts",
      "Crushed peanuts",
      "Lime wedges and cilantro",
    ],
    InstructionList: [
      "Soak noodles in warm water.",
      "Prepare sauce with tamarind, fish sauce, and sugar.",
      "Scramble eggs and set aside.",
      "Cook shrimp until pink.",
      "Add noodles and sauce.",
      "Top with peanuts, cilantro, and lime.",
    ],
    tipList: [
      "Don't oversoak noodles",
      "Cook on high heat",
      "Balance sweet and salty flavors",
      "Prepare ingredients before cooking",
    ],
  },
  {
    img: "images/Onion-Soup.avif",
    rate: "4.7",
    review: "(267 reviews)",
    prep: "15 min",
    cook: "60 min",
    serve: "4 people",
    level: "Intermediate",
    country: "Mediterranean",
    recipeTitle: "French Onion Soup",
    recipeDescription:
      "Rich beef broth with caramelized onions and melted cheese",
    recipeAlert: true,
    Calories: "380 kcal",
    Protein: "18g",
    Carbohydrates: "36g",
    Fat: "18g",
    Fiber: "4g",
    Sodium: "980mg",
    IngredientList: [
      "4 large onions, thinly sliced",
      "4 tablespoons butter",
      "1 liter beef broth",
      "1/2 cup white wine",
      "2 bay leaves",
      "Fresh thyme",
      "Baguette slices",
      "200g Gruyère cheese, grated",
    ],
    InstructionList: [
      "Melt butter and cook onions slowly for 40 minutes until caramelized.",
      "Add white wine and deglaze the pot.",
      "Pour in beef broth and herbs. Simmer for 20 minutes.",
      "Toast baguette slices until golden.",
      "Top soup with bread and cheese.",
      "Broil until cheese is melted and bubbly.",
    ],
    tipList: [
      "Do not rush onion caramelization",
      "Use quality beef broth",
      "Watch carefully while broiling",
      "Serve immediately",
    ],
  },

  {
    img: "images/Stir-Fry.avif",
    rate: "4.5",
    review: "(324 reviews)",
    prep: "15 min",
    cook: "15 min",
    serve: "4 people",
    level: "Easy",
    country: "Asian",
    recipeTitle: "Chicken Stir-Fry",
    recipeDescription: "Quick and healthy stir-fry with colorful vegetables",
    recipeAlert: false,
    Calories: "320 kcal",
    Protein: "34g",
    Carbohydrates: "18g",
    Fat: "12g",
    Fiber: "5g",
    Sodium: "840mg",
    IngredientList: [
      "500g chicken breast, sliced",
      "2 bell peppers, sliced",
      "1 broccoli head, florets",
      "2 carrots, julienned",
      "3 tablespoons soy sauce",
      "2 tablespoons oyster sauce",
      "1 tablespoon sesame oil",
      "2 cloves garlic, minced",
      "Fresh ginger, grated",
    ],
    InstructionList: [
      "Mix soy sauce, oyster sauce, and sesame oil.",
      "Cook chicken until golden and set aside.",
      "Cook garlic and ginger.",
      "Add vegetables and stir-fry.",
      "Return chicken and add sauce.",
      "Serve with rice or noodles.",
    ],
    tipList: [
      "Keep heat high",
      "Cut ingredients before cooking",
      "Do not overcrowd the wok",
      "Add nuts for crunch",
    ],
  },

  {
    img: "images/Lasagna.avif",
    rate: "4.9",
    review: "(478 reviews)",
    prep: "30 min",
    cook: "90 min",
    serve: "4 people",
    level: "Intermediate",
    country: "Italian",
    recipeTitle: "Lasagna Bolognese",
    recipeDescription:
      "Layered Italian pasta with rich meat sauce and béchamel",
    recipeAlert: true,
    Calories: "680 kcal",
    Protein: "42g",
    Carbohydrates: "58g",
    Fat: "28g",
    Fiber: "6g",
    Sodium: "920mg",
    IngredientList: [
      "12 lasagna sheets",
      "500g ground beef",
      "400g canned tomatoes",
      "1 onion, diced",
      "2 carrots, diced",
      "500ml béchamel sauce",
      "200g mozzarella, grated",
      "100g parmesan cheese",
      "Fresh basil",
    ],
    InstructionList: [
      "Cook beef with onion and carrots.",
      "Add tomatoes and simmer.",
      "Cook lasagna sheets.",
      "Layer sauce, pasta, and béchamel.",
      "Top with cheese.",
      "Bake until golden and bubbly.",
    ],
    tipList: [
      "Rest before slicing",
      "Use fresh pasta if possible",
      "Make sauce ahead",
      "Freeze leftovers",
    ],
  },

  {
    img: "images/Shrimp.jpg",
    rate: "4.8",
    review: "(356 reviews)",
    prep: "10 min",
    cook: "15 min",
    serve: "2 people",
    level: "Easy",
    country: "Seafood",
    recipeTitle: "Shrimp Scampi",
    recipeDescription: "Garlicky shrimp in white wine butter sauce",
    recipeAlert: false,
    Calories: "520 kcal",
    Protein: "36g",
    Carbohydrates: "54g",
    Fat: "18g",
    Fiber: "3g",
    Sodium: "620mg",
    IngredientList: [
      "400g large shrimp, peeled",
      "300g linguine pasta",
      "6 cloves garlic, minced",
      "1/2 cup white wine",
      "4 tablespoons butter",
      "2 tablespoons olive oil",
      "Fresh parsley",
      "Lemon juice and zest",
      "Red pepper flakes",
    ],
    InstructionList: [
      "Cook linguine and reserve pasta water.",
      "Cook garlic and pepper flakes in butter.",
      "Cook shrimp until pink.",
      "Add wine and simmer.",
      "Mix pasta with shrimp and sauce.",
      "Serve with parsley and lemon zest.",
    ],
    tipList: [
      "Do not overcook shrimp",
      "Use quality white wine",
      "Add extra lemon",
      "Serve immediately",
    ],
  },
  {
    img: "images/Vegetable-Curry.avif",
    rate: "4.6",
    review: "(289 reviews)",
    prep: "20 min",
    cook: "30 min",
    serve: "4 people",
    level: "Easy",
    country: "Asian",
    recipeTitle: "Vegetable Curry",
    recipeDescription: "Hearty vegetarian curry with coconut milk",
    recipeAlert: true,
    Calories: "380 kcal",
    Protein: "14g",
    Carbohydrates: "48g",
    Fat: "16g",
    Fiber: "12g",
    Sodium: "480mg",
    IngredientList: [
      "2 potatoes, cubed",
      "1 cauliflower, florets",
      "2 carrots, sliced",
      "1 can chickpeas",
      "400ml coconut milk",
      "3 tablespoons curry powder",
      "1 onion, diced",
      "3 cloves garlic, minced",
      "Fresh spinach",
    ],
    InstructionList: [
      "Heat oil and cook onion until soft.",
      "Add garlic and curry powder.",
      "Add potatoes and carrots.",
      "Pour in coconut milk and simmer.",
      "Add cauliflower and chickpeas.",
      "Stir in spinach and serve hot.",
    ],
    tipList: [
      "Use full-fat coconut milk",
      "Adjust curry level to taste",
      "Add tofu for extra protein",
      "Serve with basmati rice",
    ],
  },

  {
    img: "images/meat.avif",
    rate: "4.7",
    review: "(412 reviews)",
    prep: "15 min",
    cook: "240 min",
    serve: "4 people",
    level: "Easy",
    country: "American",
    recipeTitle: "BBQ Pulled Pork",
    recipeDescription: "Slow-cooked tender pork in smoky barbecue sauce",
    recipeAlert: true,
    Calories: "620 kcal",
    Protein: "48g",
    Carbohydrates: "52g",
    Fat: "22g",
    Fiber: "3g",
    Sodium: "1180mg",
    IngredientList: [
      "1kg pork shoulder",
      "1 cup BBQ sauce",
      "1/2 cup apple cider vinegar",
      "2 tablespoons brown sugar",
      "1 tablespoon paprika",
      "1 tablespoon garlic powder",
      "Burger buns",
      "Coleslaw for serving",
    ],
    InstructionList: [
      "Mix paprika, garlic powder, brown sugar, salt and pepper.",
      "Rub mixture over pork shoulder.",
      "Place pork in slow cooker with vinegar and water.",
      "Cook until tender.",
      "Shred pork and mix with BBQ sauce.",
      "Serve on buns with coleslaw.",
    ],
    tipList: [
      "Use pork shoulder for best texture",
      "Rest pork before shredding",
      "Freeze leftovers for later",
      "Homemade BBQ sauce tastes better",
    ],
  },

  {
    img: "images/Greek-Moussaka.avif",
    rate: "4.8",
    review: "(234 reviews)",
    prep: "30 min",
    cook: "60 min",
    serve: "4 people",
    level: "Intermediate",
    country: "Mediterranean",
    recipeTitle: "Greek Moussaka",
    recipeDescription: "Traditional layered eggplant casserole with lamb",
    recipeAlert: true,
    Calories: "580 kcal",
    Protein: "36g",
    Carbohydrates: "32g",
    Fat: "32g",
    Fiber: "8g",
    Sodium: "820mg",
    IngredientList: [
      "3 large eggplants, sliced",
      "500g ground lamb",
      "400g canned tomatoes",
      "1 onion, diced",
      "3 cloves garlic, minced",
      "500ml béchamel sauce",
      "100g parmesan cheese",
      "Cinnamon and oregano",
      "Olive oil",
    ],
    InstructionList: [
      "Salt eggplant and let sit for 30 minutes.",
      "Cook eggplant until softened.",
      "Cook lamb with onion, garlic, tomatoes, and spices.",
      "Layer eggplant and meat sauce.",
      "Top with béchamel and parmesan.",
      "Bake until golden brown.",
    ],
    tipList: [
      "Salt eggplant to remove bitterness",
      "Let moussaka rest before slicing",
      "Use beef if lamb is unavailable",
      "Can be made ahead",
    ],
  },

  {
    img: "images/Teriyaki.avif",
    rate: "4.7",
    review: "(367 reviews)",
    prep: "15 min",
    cook: "20 min",
    serve: "2 people",
    level: "Easy",
    country: "Asian",
    recipeTitle: "Teriyaki Chicken Bowl",
    recipeDescription: "Sweet and savory chicken over rice with vegetables",
    recipeAlert: false,
    Calories: "540 kcal",
    Protein: "42g",
    Carbohydrates: "58g",
    Fat: "14g",
    Fiber: "4g",
    Sodium: "1240mg",
    IngredientList: [
      "400g chicken thighs, sliced",
      "1/2 cup teriyaki sauce",
      "2 cups cooked rice",
      "1 broccoli head, florets",
      "1 carrot, julienned",
      "Sesame seeds",
      "Green onions, sliced",
      "1 tablespoon sesame oil",
    ],
    InstructionList: [
      "Cook chicken in sesame oil.",
      "Add teriyaki sauce and simmer.",
      "Steam vegetables until tender.",
      "Divide rice into bowls.",
      "Top with chicken and vegetables.",
      "Garnish with sesame seeds and onions.",
    ],
    tipList: [
      "Use chicken thighs for juicier meat",
      "Meal prep ahead of time",
      "Add edamame for extra protein",
      "Homemade teriyaki sauce tastes better",
    ],
  },
  {
    img: "images/Sandwich.avif",
    rate: "4.5",
    review: "(189 reviews)",
    prep: "10 min",
    cook: "5 min",
    serve: "2 people",
    level: "Easy",
    country: "Italian",
    recipeTitle: "Caprese Sandwich",
    recipeDescription:
      "Fresh Italian sandwich with mozzarella, tomato, and basil",
    recipeAlert: false,
    Calories: "480 kcal",
    Protein: "22g",
    Carbohydrates: "48g",
    Fat: "22g",
    Fiber: "3g",
    Sodium: "680mg",
    IngredientList: [
      "1 Ciabatta bread",
      "200g Fresh mozzarella , sliced",
      "2 large tomatoes, sliced",
      "Fresh basil leaves",
      "3 tablespoons pesto",
      "2 tablespoons balsamic glaze",
      "Olive oil",
      "Salt and pepper",
    ],
    InstructionList: [
      "Slice ciabatta bread in half horizontally.",
      "Toast bread lightly until just crispy.",
      "Spread pesto on both sides of bread.",
      "Layer mozzarella slices, tomato slices, and fresh basil leaves.",
      "Drizzle with olive oil and balsamic glaze. Season with salt and pepper.",
      "Close sandwich, cut in half, and serve immediately.",
    ],
    tipList: [
      "Use ripe, in-season tomatoes for best flavor",
      "Buffalo mozzarella is traditional but harder to slice",
      "Toast bread lightly - not too crispy",
      "Add prosciutto or salami for a heartier sandwich",
    ],
  },
];

// console.log(
//   rate,
//   reviews,
//   prep,
//   cook,
//   Servings,
//   level,
//   country,
//   recipeTitle,
//   recipeDescription,
//   Calories,
//   Protein,
//   Carbohydrates,
//   Fat,
//   Fiber,
//   Sodium,
//   image,
// );

function replace() {
  var random = Math.floor(Math.random() * recipe.length);
  Ingredient.innerHTML = "";
  Instruction.innerHTML = "";
  Tips.innerHTML = "";
  rate.innerHTML = `${recipe[random].rate}`;
  reviews.innerHTML = `${recipe[random].review}`;
  prep.innerHTML = `${recipe[random].prep}`;
  cook.innerHTML = `${recipe[random].cook}`;
  Servings.innerHTML = `${recipe[random].serve}`;
  level.innerHTML = `${recipe[random].level}`;
  country.innerHTML = `${recipe[random].country}`;
  recipeTitle.innerHTML = `${recipe[random].recipeTitle}`;
  recipeDescription.innerHTML = `${recipe[random].recipeDescription}`;
  Calories.innerHTML = `${recipe[random].Calories}`;
  Protein.innerHTML = `${recipe[random].Protein}`;
  Carbohydrates.innerHTML = `${recipe[random].Carbohydrates}`;
  Fat.innerHTML = `${recipe[random].Fat}`;
  Fiber.innerHTML = `${recipe[random].Fiber}`;
  Sodium.innerHTML = `${recipe[random].Sodium}`;
  image.src = `${recipe[random].img}`;

  for (var i = 0; i < recipe[random].IngredientList.length; i++) {
    Ingredient.innerHTML += `<li class="d-flex gap-2 mb-3 fs-6 align-items-center my-2">
                          <h4
                            class="num mb-0 text-white rounded-circle d-flex align-items-center justify-content-center"
                          >
                            ${i + 1}
                          </h4>
                          <span class="text-dark-emphasis"
                            >${recipe[random].IngredientList[i]}
                          </span>
                        </li>`;
  }
  for (var i = 0; i < recipe[random].InstructionList.length; i++) {
    Instruction.innerHTML += `<li class="d-flex gap-3 mb-3 d-flex align-items-center ">
                            <div
                              class="num d-flex text-white rounded-4 fs-4 justify-content-center align-items-center"
                            >
                              ${i + 1}
                            </div>
                            <p class="fs-6 m-0">
                              ${recipe[random].InstructionList[i]}
                            </p>
                          </li>`;
  }
  for (var i = 0; i < recipe[random].tipList.length; i++) {
    Tips.innerHTML += `<div
                          class="tip d-flex gap-2 my-2 p-4 rounded-4 align-items-center"
                        >
                          <i><i class="fa-solid fa-circle-check fs-5"></i></i>
                          <p class="mb-0">
                            ${recipe[random].tipList[i]}
                          </p>
                        </div>`;
  }
  if (recipe[random].recipeAlert === true) {
    recipe_Alert.classList.remove("d-none");
  } else {
    recipe_Alert.classList.add("d-none");
  }
}
replace();
